/**
 * Personalized Study Mode.
 *  • Flashcards with Leitner-box spaced repetition (box 1 = see often, box 5 = mastered).
 *  • Multiple-choice quizzes with explanations and "watch this moment" links.
 *  • Mastered nodes get a hand-drawn ✓ on the map; progress feeds gamification.
 * Cards are generated by the backend LLM, or locally from "Term: meaning" nodes when offline.
 */
import { getProgress, saveProgress } from '../lib/storage.js';
import { el, fmtTime, modal, plain, toast, truncateText } from './shared.js';

export class StudyMode {
  constructor({ api, model, renderer, seek, gamify }) {
    Object.assign(this, { api, model, renderer, seek, gamify });
  }

  async loadProgress() {
    this.progress = await getProgress(this.model.map.id);
    this.renderer.setMastered(this.progress.mastered || []);
    return this.progress;
  }

  async open({ focusIds = null, tab = 'cards' } = {}) {
    await this.loadProgress();
    const { body, close } = modal('🎓 Study mode', { wide: true });
    this.body = body;
    this.close = close;
    if (!this.progress.set || focusIds) await this.#generate(focusIds);
    this.#tabs(tab);
  }

  async #generate(focusIds) {
    this.body.replaceChildren(el('div', { class: 'study-loading' }, [el('div', { class: 'scribble-spinner' }), 'Writing flashcards and quiz questions…']));
    let set;
    try {
      set = this.api.online ? await this.api.study(this.model.toJSON(), 14, focusIds) : localStudySet(this.model, 14);
    } catch (err) {
      toast(`Backend study generation failed (${err.message}); using offline cards.`, { type: 'error' });
      set = localStudySet(this.model, 14);
    }
    this.progress.set = set;
    this.progress.cards = {};
    await saveProgress(this.progress);
  }

  #tabs(active) {
    const { flashcards = [], quiz = [] } = this.progress.set || {};
    const tabs = el('div', { class: 'tabs' }, [
      el('button', { class: `tab ${active === 'cards' ? 'on' : ''}`, onclick: () => this.#tabs('cards') }, `Flashcards (${flashcards.length})`),
      el('button', { class: `tab ${active === 'quiz' ? 'on' : ''}`, onclick: () => this.#tabs('quiz') }, `Quiz (${quiz.length})`),
      el('button', { class: `tab ${active === 'progress' ? 'on' : ''}`, onclick: () => this.#tabs('progress') }, 'Progress'),
      el('button', {
        class: 'btn btn-small btn-ghost push-right',
        onclick: async () => {
          await this.#generate(null);
          this.#tabs(active);
        },
      }, '↻ New set'),
    ]);
    const content = el('div', { class: 'study-content' });
    this.body.replaceChildren(tabs, content);
    if (active === 'cards') this.#cards(content);
    else if (active === 'quiz') this.#quiz(content);
    else this.#progressView(content);
  }

  // --- flashcards ----------------------------------------------------------
  #nextCard() {
    const cards = this.progress.set?.flashcards || [];
    const boxes = this.progress.cards;
    const due = cards
      .map((c) => ({ c, box: boxes[c.id]?.box || 1, seen: boxes[c.id]?.seen || 0 }))
      .filter((x) => x.box < 5)
      .sort((a, b) => a.box - b.box || a.seen - b.seen);
    return due[0]?.c || null;
  }

  #cards(host) {
    const card = this.#nextCard();
    if (!card) {
      host.append(el('div', { class: 'study-done' }, ['🏆 All cards mastered! ', el('button', { class: 'btn', onclick: () => this.#tabs('quiz') }, 'Take the quiz')]));
      return;
    }
    const box = this.progress.cards[card.id]?.box || 1;
    const face = el('div', { class: 'flashcard', tabindex: 0, role: 'button', 'aria-label': 'Flip card' }, [
      el('div', { class: 'flash-front' }, card.front),
      el('div', { class: 'flash-back' }, card.back),
    ]);
    const flip = () => face.classList.toggle('flipped');
    face.addEventListener('click', flip);
    face.addEventListener('keydown', (e) => (e.key === ' ' || e.key === 'Enter') && (e.preventDefault(), flip()));

    const grade = async (delta) => {
      const entry = this.progress.cards[card.id] || { box: 1, seen: 0 };
      entry.box = delta < 0 ? 1 : Math.min(5, entry.box + delta);
      entry.seen += 1;
      this.progress.cards[card.id] = entry;
      if (delta > 0) this.gamify?.track('flashcard_correct');
      if (entry.box >= 4 && card.nodeId && !this.progress.mastered.includes(card.nodeId)) {
        this.progress.mastered.push(card.nodeId);
        this.renderer.setMastered(this.progress.mastered);
      }
      await saveProgress(this.progress);
      this.#tabs('cards');
    };

    host.append(
      el('div', { class: 'leitner' }, [1, 2, 3, 4, 5].map((b) => el('span', { class: `box ${b === box ? 'on' : ''}` }, `Box ${b}`))),
      face,
      el('p', { class: 'hint' }, 'Click the card (or press Space) to reveal the answer.'),
      el('div', { class: 'panel-row center' }, [
        el('button', { class: 'btn btn-danger', onclick: () => grade(-1) }, '↺ Again'),
        el('button', { class: 'btn', onclick: () => grade(1) }, '✓ Good'),
        el('button', { class: 'btn btn-accent', onclick: () => grade(2) }, '★ Easy'),
      ]),
      this.#nodeLinks(card),
    );
    face.focus();
  }

  #nodeLinks(item) {
    if (!item.nodeId || !this.model.get(item.nodeId)) return el('span');
    const node = this.model.get(item.nodeId);
    return el('div', { class: 'panel-row center subtle' }, [
      el('button', {
        class: 'btn btn-ghost btn-small',
        onclick: () => {
          this.close();
          this.renderer.reveal(node.id);
          this.renderer.select(node.id);
          this.renderer.centerOn(node.id);
        },
      }, '🧠 Show in map'),
      node.start !== null && node.start !== undefined ? el('button', { class: 'btn btn-ghost btn-small', onclick: () => this.seek(node) }, `▶ Watch ${fmtTime(node.start)}`) : null,
    ]);
  }

  // --- quiz ------------------------------------------------------------------
  #quiz(host, index = 0, score = 0) {
    const quiz = this.progress.set?.quiz || [];
    if (!quiz.length) {
      host.append(el('p', {}, 'Not enough concepts for a quiz yet.'));
      return;
    }
    if (index >= quiz.length) {
      const pct = Math.round((score / quiz.length) * 100);
      host.replaceChildren(
        el('div', { class: 'study-done' }, [
          el('div', { class: 'score-burst' }, `${pct}%`),
          el('p', {}, `${score} / ${quiz.length} correct${pct >= 80 ? ' — excellent!' : pct >= 50 ? ' — keep going!' : ' — review the highlighted nodes.'}`),
          el('button', { class: 'btn', onclick: () => this.#tabs('quiz') }, 'Retry'),
        ]),
      );
      return;
    }
    const q = quiz[index];
    const feedback = el('div', { class: 'quiz-feedback' });
    const options = q.options.map((option, i) =>
      el('button', {
        class: 'quiz-option',
        onclick: async () => {
          const correct = i === q.answer;
          options.forEach((b, j) => {
            b.disabled = true;
            b.classList.toggle('right', j === q.answer);
            b.classList.toggle('wrong', j === i && !correct);
          });
          this.progress.quizTotal = (this.progress.quizTotal || 0) + 1;
          if (correct) {
            this.progress.quizCorrect = (this.progress.quizCorrect || 0) + 1;
            this.gamify?.track('quiz_correct');
          }
          await saveProgress(this.progress);
          feedback.replaceChildren(
            el('strong', {}, correct ? '✓ Correct! ' : '✗ Not quite. '),
            q.explanation || '',
            this.#nodeLinks(q),
            el('button', { class: 'btn', onclick: () => this.#quiz(host.replaceChildren() || host, index + 1, score + (correct ? 1 : 0)) }, index + 1 < quiz.length ? 'Next →' : 'See score'),
          );
        },
      }, option),
    );
    host.replaceChildren(
      el('p', { class: 'quiz-count' }, `Question ${index + 1} of ${quiz.length}`),
      el('h3', { class: 'quiz-question' }, q.question),
      el('div', { class: 'quiz-options' }, options),
      feedback,
    );
  }

  #progressView(host) {
    const cards = this.progress.set?.flashcards || [];
    const boxes = [1, 2, 3, 4, 5].map((b) => cards.filter((c) => (this.progress.cards[c.id]?.box || 1) === b).length);
    const explored = this.progress.explored?.length || 0;
    const total = this.model.nodes().length;
    host.append(
      el('div', { class: 'progress-grid' }, [
        stat('Explored nodes', `${explored}/${total}`, explored / Math.max(total, 1)),
        stat('Mastered concepts', String(this.progress.mastered.length), this.progress.mastered.length / Math.max(cards.length, 1)),
        stat('Quiz accuracy', this.progress.quizTotal ? `${Math.round((this.progress.quizCorrect / this.progress.quizTotal) * 100)}%` : '—', this.progress.quizTotal ? this.progress.quizCorrect / this.progress.quizTotal : 0),
      ]),
      el('h4', {}, 'Leitner boxes'),
      el('div', { class: 'leitner big' }, boxes.map((n, i) => el('span', { class: 'box', style: `--fill:${n / Math.max(cards.length, 1)}` }, `Box ${i + 1}: ${n}`))),
    );
  }
}

function stat(label, value, ratio) {
  return el('div', { class: 'stat' }, [
    el('div', { class: 'stat-value' }, value),
    el('div', { class: 'stat-label' }, label),
    el('div', { class: 'sketch-bar' }, el('span', { style: `width:${Math.round(Math.min(1, ratio) * 100)}%` })),
  ]);
}

/** Offline generation mirroring backend/app/features/study.py fallbacks. */
export function localStudySet(model, count = 12) {
  const concepts = [];
  model.walk((node, parent) => {
    if (['concept', 'detail'].includes(node.type) && plain(node.text)) concepts.push({ node, section: parent ? plain(parent.text) : '' });
  });
  const split = ({ node, section }) => {
    const text = plain(node.text);
    if (text.includes(':')) return [text.split(':')[0].trim(), text.slice(text.indexOf(':') + 1).trim()];
    return [text, node.summary || section];
  };
  const pairs = concepts.map((c) => [c, ...split(c)]).filter(([, , meaning]) => meaning);
  const id = () => crypto.randomUUID().slice(0, 8);
  const flashcards = pairs.slice(0, count).map(([c, term, meaning]) => ({ id: id(), front: `What is meant by “${term}”?`, back: meaning, nodeId: c.node.id, start: c.node.start }));
  const quiz = [];
  for (const [c, term, meaning] of pairs) {
    const distractors = pairs.filter(([, t, m]) => t !== term && m !== meaning).map(([, , m]) => m);
    if (distractors.length < 3) break;
    const options = distractors.sort(() => Math.random() - 0.5).slice(0, 3).concat(meaning).sort(() => Math.random() - 0.5);
    quiz.push({ id: id(), question: `Which statement best describes “${term}”?`, options: options.map((o) => truncateText(o, 140)), answer: options.indexOf(meaning), explanation: meaning, nodeId: c.node.id, start: c.node.start });
    if (quiz.length >= Math.max(4, count / 2)) break;
  }
  return { flashcards, quiz, provider: 'offline' };
}
